
package com.paulrybitskyi.gamedge.common.data.games.datastores.database

import com.paulrybitskyi.gamedge.core.providers.TimestampProvider
import com.paulrybitskyi.gamedge.database.games.entities.DbLikedGame
import com.paulrybitskyi.hiltbinder.BindType
import javax.inject.Inject
import javax.inject.Singleton

private const val ENTITY_AUTOGENERATED_ID_INDICATOR = 0

internal interface LikedGameFactory {
    fun createLikedGame(gameId: Int): DbLikedGame
}

@Singleton
@BindType
internal class LikedGameFactoryImpl @Inject constructor(
    private val timestampProvider: TimestampProvider,
) : LikedGameFactory {

    override fun createLikedGame(gameId: Int): DbLikedGame {
        return DbLikedGame(
            id = ENTITY_AUTOGENERATED_ID_INDICATOR,
            gameId = gameId,
            likeTimestamp = timestampProvider.getUnixTimestamp(),
        )
    }
}
